stages:
  - setup
  - format
  - build
  - test
  - python-lint

variables:
  DOTNET_ROOT: "/usr/share/dotnet"
  PATH: "$DOTNET_ROOT:$PATH"

cache:
  paths:
    - .nuget/packages/
    - src/**/bin/
    - src/**/obj/

setup:
  stage: setup
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip fsharp mono-complete
  script:
    - dotnet --version
    - python3 --version

format:
  stage: format
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet new tool-manifest
    - dotnet tool install fantomas-tool --version "4.*"
    - dotnet fantomas src --recurse
    - dotnet fantomas tests --recurse
  artifacts:
    paths:
      - src/

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build src --configuration Release
  artifacts:
    paths:
      - src/**/bin/Release/