image: ubuntu:22.04

stages:
  - setup
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

before_script:
  - apt-get update -y
  - apt-get install -y wget apt-transport-https
  - wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - apt-get update -y
  - apt-get install -y dotnet-sdk-8.0

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore
  artifacts:
    paths:
      - bin/Release/net8.0/
    expire_in: 1 week

test:
  stage: test
  script:
    - dotnet test --no-restore --verbosity normal

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add your deployment scripts here
  only:
    - main
