image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore
  artifacts:
    paths:
      - bin/Release/net6.0/
    expire_in: 1 week

test:
  stage: test
  script:
    - dotnet test --no-restore --verbosity normal

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add your deployment scripts here
  only:
    - main