image: ubuntu:20.04

stages:
  - build
  - lint
  - format
  - test
  - run

before_script:
  - apt-get update -y
  - apt-get install -y dotnet-sdk-7.0
  - apt-get install -y python3 python3-pip fsharp
  - pip3 install pylint
  - dotnet tool install --global fantomas-tool --version "5.*"  
  - dotnet tool install --global FSharpLint.Tool --version "0.14.*"  

build:
  stage: build
  script:
    - dotnet restore src
    - dotnet build src --no-restore --configuration Release
  artifacts:
    paths:
      - src/bin/Release

lint:
  stage: lint
  script:
    - fsharplint lint src/task7/task7.fs
    - fsharplint lint src/task26/task26.fs

format:
  stage: format
  script:
    - fantomas src --recurse
  artifacts:
    paths:
      - src
  only:
    - merge_requests 

test:
  stage: test
  script:
    - dotnet test src --no-restore
  artifacts:
    paths:
      - ./TestResults

run_python:
  stage: run
  script:
    - pylint src/task7.py src/task26.py
    - python3 src/task7.py 
    - python3 src/task26.py  
