name: module18

on:
  push:
    branches:
      - master
    paths:
      - "euler"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dotnet-sdk-8.0 python3 python3-pip fsharp mono-complete

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload formatted files
        uses: actions/upload-artifact@v4
        with:
          name: formatted-src
          path: euler/18

  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build task
        working-directory: euler/18
        run: |
          dotnet build --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: euler/18/**/bin/Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run application
        working-directory: euler/18
        run: |
          dotnet run --configuration Release

      - name: Run tests
        working-directory: euler/18/18test
        run: dotnet test
